# Ports
APP_DEFAULT_PORT = 9999

# App
APP_TITLE = "API Artisan"
APP_FAVICON = "🚀"
APP_SHOW_WELCOME_MESSAGE = False

# Debug
APP_DEFAULT_DEBUG = False

# Screensize
DEFAULT_SCREEN_WIDTH = 1200
DEFAULT_SCREEN_HEIGHT = 800
